services:
  bwapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: alesandocker/bwapp-compose:v1
    container_name: bwapp
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - bwapp_www:/var/www/html
      - bwapp_mysql:/var/lib/mysql

volumes:
  bwapp_www:
  bwapp_mysql:

