services:
  bwapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: alesandocker/bwapp-docker
    container_name: bwapp
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - bwapp_www:/var/www/html
      - bwapp_mysql:/var/lib/mysql

volumes:
  bwapp_www:
  bwapp_mysql: